# Generated by Django 4.2.4 on 2024-01-05 04:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_is_staff_myuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cared_industry',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=50), default=[], size=None),
        ),
    ]
