# Generated by Django 4.2.4 on 2024-01-05 04:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_myuser_cared_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cared_industry',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
