# Generated by Django 4.2.4 on 2024-01-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_myuser_career_alter_myuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='career',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='school',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
