# Generated by Django 4.2.4 on 2024-01-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_myuser_career_alter_myuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='career',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='school',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
